source 'https://rubygems.org'
gem 'savon', '<3.0.0'
gem 'pry'
gem 'ruby-progressbar'
gem 'eye'
gem 'redis'
gem 'eye-rotate'
gem 'bson_ext'
gem 'mongo', '~> 1.11.1'
gem 'pry-rescue'
gem 'pry-stack_explorer'
gem 'pry-remote-em'
gem 'rest_client'
gem 'pg'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rbvmomi'
gem 'slack-api'
gem 'zipruby'
gem 'docker-api', :require => 'docker'
gem 'hashie'
