source 'https://rubygems.org'
gem 'savon', '<3.0.0'
gem 'pry'
gem 'ruby-progressbar'
gem 'redis'
gem 'pry-rescue'
#gem 'pry-stack_explorer'
gem 'pry-remote-em'
gem 'rest-client'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rbvmomi'
gem 'slack-api'
gem 'zipruby'
gem 'docker-api', :require => 'docker'
gem 'hashie'
gem 'r509'
gem 'aws-sdk', '2.0.0.pre'
gem 'net-ldap'
gem 'hamster'
